# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
version: "3.9"
services:
  configurator:
    build:
      context: .
    command: ["uvicorn", "--factory", "job_function_configurator.main:create_app", "--host", "0.0.0.0", "--reload"]
    env_file:
      - docker.env
    environment:
      LOG_LEVEL: DEBUG
    networks:
      - os2mo_default
    volumes:
      - ./job_function_configurator:/opt/app/
    ports:
      - "8200:8000"

networks:
  os2mo_default:
    external: true
