# SPDX-FileCopyrightText: 2022 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
# ########################## DO NOT EDIT FILE ############################
# All code in this module is auto generated by Quicktype
# See https://github.com/quicktype/quicktype for general documentation.
# 1 - Make a "name_of_your_file.graphql" file.
# 2 - Contents of file must be the query, you wish to generate models from, uncommented.
# 3 - Stand in directory of your "name_of_your_file.graphql" file and run the
# following command with the path to the query to generate from:
# $ quicktype --src-lang graphql --lang py --python-version 3.7 \
#    --graphql-introspect https://moradev.magentahosted.dk/graphql/v7 \
#    get_job_functions.graphql --just-types
#
# 4 - The model will be shown in terminal. Copy and paste the output in your file.
# query GetJobFunctions {
#   engagements{
#     objects {
#       current {
#         extension_2
#         is_primary
#         job_function {
#           name
#           user_key
#           uuid
#         }
#         primary {
#           name
#           user_key
#           name
#           uuid
#         }
#         employee {
#           uuid
#           addresses {
#             name
#             user_key
#             address_type {
#               scope
#               user_key
#               name
#             }
#           }
#         }
#       }
#       uuid
#     }
#   }
# }

from dataclasses import dataclass
from typing import Optional, List


@dataclass
class AddressClass:
    user_key: str
    name: str
    scope: Optional[str] = None


@dataclass
class Address:
    user_key: str
    address_type: AddressClass
    name: Optional[str] = None


@dataclass
class Employee:
    uuid: str
    addresses: List[Address]


@dataclass
class EngagementClass:
    name: str
    user_key: str
    uuid: str


@dataclass
class Engagement:
    is_primary: bool
    job_function: EngagementClass
    employee: List[Employee]
    extension_2: Optional[str] = None
    primary: Optional[EngagementClass] = None


@dataclass
class EngagementResponse:
    uuid: str
    current: Optional[Engagement] = None


@dataclass
class EngagementResponsePaged:
    objects: List[EngagementResponse]


@dataclass
class Data:
    engagements: EngagementResponsePaged


@dataclass
class Error:
    message: str


@dataclass
class GetJobFunctions:
    data: Optional[Data] = None
    errors: Optional[List[Error]] = None
