# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from collections.abc import AsyncIterator
from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.main import construct_mo_client

from job_function_configurator.autogenerated_graphql_client import ClassCreateInput
from job_function_configurator.autogenerated_graphql_client import EmployeeCreateInput
from job_function_configurator.autogenerated_graphql_client import FacetCreateInput
from job_function_configurator.autogenerated_graphql_client import GraphQLClient
from job_function_configurator.autogenerated_graphql_client import (
    OrganisationUnitCreateInput,
)
from job_function_configurator.autogenerated_graphql_client import RAValidityInput
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateClassClassCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateFacetFacetCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from job_function_configurator.autogenerated_graphql_client import ValidityInput
from job_function_configurator.config import get_settings
from job_function_configurator.config import JobFunctionSettings
from job_function_configurator.main import create_app
from job_function_configurator.main import GRAPHQL_VERSION

# Long before any validity used in the tests, so everything we create is
# current no matter when the tests are run.
LONG_TIME_AGO = datetime(1970, 1, 1, tzinfo=ZoneInfo("Europe/Copenhagen"))


@pytest.fixture
def settings() -> JobFunctionSettings:
    return get_settings()


@pytest.fixture
async def app() -> FastAPI:
    return create_app()


@pytest.fixture
async def graphql_client(
    settings: JobFunctionSettings,
) -> AsyncIterator[GraphQLClient]:
    """The integration's own GraphQL client, for arranging and asserting."""
    async with construct_mo_client(settings.fastramqpi) as mo_client:
        graphql_client = GraphQLClient(
            url=f"{settings.fastramqpi.mo_url}/graphql/v{GRAPHQL_VERSION}",
            http_client=mo_client,
        )
        async with graphql_client as client:
            yield client


@pytest.fixture
async def engagement_job_function_facet(
    graphql_client: GraphQLClient,
) -> TestingCreateFacetFacetCreate:
    """A facet to create the tests' classes in.

    OS2mo does not check that a class is in the facet one would expect it to be
    in, so we create our own facet rather than depending on the facets of
    whichever dataset OS2mo happens to be loaded with.
    """
    return await graphql_client._testing__create_facet(
        FacetCreateInput(
            user_key="engagement_job_function",
            validity=ValidityInput(from_=LONG_TIME_AGO),
        )
    )


@pytest.fixture
async def create_class(
    graphql_client: GraphQLClient,
    engagement_job_function_facet: TestingCreateFacetFacetCreate,
) -> Callable[..., Awaitable[TestingCreateClassClassCreate]]:
    async def inner(
        user_key: str, name: str, scope: str | None = None
    ) -> TestingCreateClassClassCreate:
        return await graphql_client._testing__create_class(
            ClassCreateInput(
                user_key=user_key,
                name=name,
                scope=scope,
                facet_uuid=engagement_job_function_facet.uuid,
                validity=ValidityInput(from_=LONG_TIME_AGO),
            )
        )

    return inner


@pytest.fixture
async def engagement_type(
    graphql_client: GraphQLClient,
) -> TestingCreateClassClassCreate:
    """An engagement type, in a facet of its own.

    Tests that read every field of an engagement need the engagement type to be
    a class that actually exists, as OS2mo cannot resolve a dangling reference.
    """
    facet = await graphql_client._testing__create_facet(
        FacetCreateInput(
            user_key="engagement_type",
            validity=ValidityInput(from_=LONG_TIME_AGO),
        )
    )
    return await graphql_client._testing__create_class(
        ClassCreateInput(
            user_key="test-engagement-type",
            name="Employee",
            facet_uuid=facet.uuid,
            validity=ValidityInput(from_=LONG_TIME_AGO),
        )
    )


@pytest.fixture
async def primary_class(
    graphql_client: GraphQLClient,
) -> TestingCreateClassClassCreate:
    """A class marking an engagement as primary, in the `primary_type` facet.

    OS2mo considers an engagement primary if its `primary` class has a scope of
    at least 3000.
    """
    facet = await graphql_client._testing__create_facet(
        FacetCreateInput(
            user_key="primary_type",
            validity=ValidityInput(from_=LONG_TIME_AGO),
        )
    )
    return await graphql_client._testing__create_class(
        ClassCreateInput(
            user_key="primary",
            name="Primary",
            scope="3000",
            facet_uuid=facet.uuid,
            validity=ValidityInput(from_=LONG_TIME_AGO),
        )
    )


@pytest.fixture
async def default_employee(
    graphql_client: GraphQLClient,
) -> TestingCreateEmployeeEmployeeCreate:
    return await graphql_client._testing__create_employee(
        EmployeeCreateInput(
            given_name="Bruce",
            surname="Lee",
        )
    )


@pytest.fixture
async def default_org_unit(
    graphql_client: GraphQLClient,
) -> TestingCreateOrgUnitOrgUnitCreate:
    return await graphql_client._testing__create_org_unit(
        OrganisationUnitCreateInput(
            name="E Corp",
            org_unit_type=uuid4(),
            validity=RAValidityInput(from_=LONG_TIME_AGO),
        )
    )
