# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0

from collections.abc import Awaitable
from collections.abc import Callable
from datetime import datetime
from uuid import UUID
from zoneinfo import ZoneInfo

import pytest
from fastapi import FastAPI
from fastramqpi.pytest_plugin import run_server
from fastramqpi.pytest_util import retry
from more_itertools import one

from job_function_configurator.autogenerated_graphql_client import (
    EngagementCreateInput,
)
from job_function_configurator.autogenerated_graphql_client import (
    EngagementUpdateInput,
)
from job_function_configurator.autogenerated_graphql_client import GraphQLClient
from job_function_configurator.autogenerated_graphql_client import ITSystemCreateInput
from job_function_configurator.autogenerated_graphql_client import ITUserCreateInput
from job_function_configurator.autogenerated_graphql_client import RAOpenValidityInput
from job_function_configurator.autogenerated_graphql_client import RAValidityInput
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateClassClassCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateEmployeeEmployeeCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingCreateOrgUnitOrgUnitCreate,
)
from job_function_configurator.autogenerated_graphql_client import (
    TestingGetEngagementTimelineEngagementsObjectsObjects as EngagementValidity,
)
from job_function_configurator.config import JobFunctionSettings

TZ = ZoneInfo("Europe/Copenhagen")

# Boundaries of the validity periods used by the tests. The current period is
# the one containing today.
T_PAST = datetime(2001, 1, 1, tzinfo=TZ)
T_CURRENT = datetime(2002, 1, 1, tzinfo=TZ)
T_FUTURE = datetime(3000, 1, 1, tzinfo=TZ)

PAST = "past"
CURRENT = "current"
FUTURE = "future"

ENGAGEMENT_USER_KEY = "12345"

# The IT system to look for IT users in. Given explicitly, rather than relying
# on the default, so the tests do not depend on the IT systems of whichever
# dataset OS2mo happens to be loaded with.
ITSYSTEM_USER_KEY = "test_active_directory"


EXTENSION_FIELDS = {f"extension_{i}" for i in range(1, 11)}


def extension_fields(period: str, **overrides: str) -> dict[str, str]:
    """Values for the extension fields, labelled with the period they are in.

    `extension_3` is included so the tests can tell the value the integration
    writes apart from the one it was given.
    """
    return {name: f"{period} {name}" for name in EXTENSION_FIELDS} | overrides


async def get_engagement_timeline(
    graphql_client: GraphQLClient,
    engagement_uuid: UUID,
) -> list[EngagementValidity]:
    """Every validity period of the engagement, with all of their fields."""
    engagements = await graphql_client._testing__get_engagement_timeline(
        engagement_uuid
    )
    return one(engagements.objects).objects


async def touch_engagement(
    graphql_client: GraphQLClient,
    engagement_uuid: UUID,
) -> None:
    """Make OS2mo emit an event for the engagement, without changing it.

    Every attribute of the current period is written back with the value it
    already has, over the exact validity of that period.
    """
    timeline = await get_engagement_timeline(graphql_client, engagement_uuid)
    current = one(period for period in timeline if period.validity.from_ == T_CURRENT)

    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement_uuid,
            validity=RAValidityInput(
                from_=current.validity.from_,
                to=current.validity.to,
            ),
            user_key=current.user_key,
            primary=current.primary.uuid if current.primary is not None else None,
            person=one(current.person).uuid,
            org_unit=one(current.org_unit).uuid,
            engagement_type=current.engagement_type.uuid,
            job_function=current.job_function.uuid,
            **current.dict(include=EXTENSION_FIELDS),
        )
    )


def assert_only_current_extension_3_changed(
    before: list[EngagementValidity],
    after: list[EngagementValidity],
    expected_extension_3: str,
) -> None:
    """The integration writes `extension_3` of the current period. Nothing else.

    Neither the other fields of the current period, nor the past and the future
    periods, may be touched.
    """
    assert len(before) == 3
    assert len(after) == 3
    past_before, current_before, future_before = before
    past_after, current_after, future_after = after

    assert current_after.extension_3 == expected_extension_3
    assert (
        current_after.copy(update={"extension_3": current_before.extension_3})
        == current_before
    )

    assert past_after == past_before
    assert future_after == future_before


@pytest.mark.integration_test
async def test_job_function_name_is_written_to_extension_3(
    app: FastAPI,
    graphql_client: GraphQLClient,
    create_class: Callable[..., Awaitable[TestingCreateClassClassCreate]],
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    An ordinary engagement gets the name of its job function written.

    The engagement has a past, a current and a future validity period, and the
    integration must leave everything alone but `extension_3` of the current
    period.
    """
    # Arrange
    job_function = await create_class(user_key="baker", name="Baker")

    # An engagement valid from T_PAST and onwards, ...
    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            user_key=ENGAGEMENT_USER_KEY,
            validity=RAValidityInput(from_=T_PAST),
            org_unit=default_org_unit.uuid,
            engagement_type=engagement_type.uuid,
            job_function=job_function.uuid,
            person=default_employee.uuid,
            **extension_fields(PAST),
        )
    )
    # ... which is cut into a past, a current and a future period, each with
    # its own values in the other extension fields
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_CURRENT),
            **extension_fields(CURRENT),
        )
    )
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_FUTURE),
            **extension_fields(FUTURE),
        )
    )

    before = await get_engagement_timeline(graphql_client, engagement.uuid)

    # Act - touching the engagement makes OS2mo emit an event for it, now that
    # the integration is listening. The touch itself changes nothing.
    async with run_server(app):
        await touch_engagement(graphql_client, engagement.uuid)

        # Assert - the job function name is written to the current period
        @retry()
        async def assertions() -> None:
            after = await get_engagement_timeline(graphql_client, engagement.uuid)
            assert_only_current_extension_3_changed(before, after, "Baker")

        await assertions()


@pytest.mark.integration_test
@pytest.mark.envvar({"BLACKLISTED_KEYS": '["1550"]'})
async def test_blacklisted_job_function_is_not_written_to_extension_3(
    app: FastAPI,
    graphql_client: GraphQLClient,
    settings: JobFunctionSettings,
    create_class: Callable[..., Awaitable[TestingCreateClassClassCreate]],
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    engagement_type: TestingCreateClassClassCreate,
) -> None:
    """
    A blacklisted job function is replaced by the configured empty value.
    """
    # Arrange
    job_function = await create_class(user_key="1550", name="Secret Agent")

    # An engagement valid from T_PAST and onwards, ...
    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            user_key=ENGAGEMENT_USER_KEY,
            validity=RAValidityInput(from_=T_PAST),
            org_unit=default_org_unit.uuid,
            engagement_type=engagement_type.uuid,
            job_function=job_function.uuid,
            person=default_employee.uuid,
            **extension_fields(PAST),
        )
    )
    # ... which is cut into a past, a current and a future period, each with
    # its own values in the other extension fields
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_CURRENT),
            **extension_fields(CURRENT),
        )
    )
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_FUTURE),
            **extension_fields(FUTURE),
        )
    )

    before = await get_engagement_timeline(graphql_client, engagement.uuid)

    # Act
    async with run_server(app):
        await touch_engagement(graphql_client, engagement.uuid)

        # Assert - the secret job function is nowhere to be found
        @retry()
        async def assertions() -> None:
            after = await get_engagement_timeline(graphql_client, engagement.uuid)
            assert_only_current_extension_3_changed(
                before, after, settings.empty_content_for_extension_field_update
            )
            assert all(
                "Secret Agent" not in (period.extension_3 or "") for period in after
            )

        await assertions()


@pytest.mark.integration_test
@pytest.mark.envvar({"ITSYSTEM_USER_KEY": ITSYSTEM_USER_KEY})
async def test_ad_job_description_wins_for_primary_engagement(
    app: FastAPI,
    graphql_client: GraphQLClient,
    create_class: Callable[..., Awaitable[TestingCreateClassClassCreate]],
    default_employee: TestingCreateEmployeeEmployeeCreate,
    default_org_unit: TestingCreateOrgUnitOrgUnitCreate,
    engagement_type: TestingCreateClassClassCreate,
    primary_class: TestingCreateClassClassCreate,
) -> None:
    """
    `extension_2` holds the AD job description.

    It takes precedence over the job function when the engagement is the
    employee's primary one and the employee has an IT user in the configured IT
    system. Each period has its own AD job description, and the one of the
    current period is the one to use.
    """
    # Arrange
    job_function = await create_class(user_key="baker", name="Baker")

    itsystem = await graphql_client._testing__create_it_system(
        ITSystemCreateInput(
            user_key=ITSYSTEM_USER_KEY,
            name="Active Directory",
            validity=RAOpenValidityInput(from_=T_PAST),
        )
    )
    await graphql_client._testing__create_it_user(
        ITUserCreateInput(
            user_key="AD",
            itsystem=itsystem.uuid,
            person=default_employee.uuid,
            validity=RAValidityInput(from_=T_PAST),
        )
    )

    # An engagement valid from T_PAST and onwards, ...
    engagement = await graphql_client._testing__create_engagement(
        EngagementCreateInput(
            user_key=ENGAGEMENT_USER_KEY,
            validity=RAValidityInput(from_=T_PAST),
            org_unit=default_org_unit.uuid,
            engagement_type=engagement_type.uuid,
            job_function=job_function.uuid,
            person=default_employee.uuid,
            primary=primary_class.uuid,
            **extension_fields(PAST, extension_2="Baker of the past"),
        )
    )
    # ... which is cut into a past, a current and a future period, each with
    # its own AD job description in extension_2
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_CURRENT),
            **extension_fields(CURRENT, extension_2="Head Baker"),
        )
    )
    await graphql_client._testing__update_engagement(
        EngagementUpdateInput(
            uuid=engagement.uuid,
            validity=RAValidityInput(from_=T_FUTURE),
            **extension_fields(FUTURE, extension_2="Baker of the future"),
        )
    )

    before = await get_engagement_timeline(graphql_client, engagement.uuid)

    # Act
    async with run_server(app):
        await touch_engagement(graphql_client, engagement.uuid)

        # Assert - the AD job description of the current period is used
        @retry()
        async def assertions() -> None:
            after = await get_engagement_timeline(graphql_client, engagement.uuid)
            assert_only_current_extension_3_changed(before, after, "Head Baker")

        await assertions()
