# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from typing import Annotated

from fastapi import Depends
from fastramqpi.depends import from_user_context
from fastramqpi.ramqp.depends import from_context

from job_function_configurator.autogenerated_graphql_client import (
    GraphQLClient as _GraphQLClient,
)
from job_function_configurator.config import JobFunctionSettings as _JobFunctionSettings

GraphQLClient = Annotated[_GraphQLClient, Depends(from_context("graphql_client"))]

Settings = Annotated[_JobFunctionSettings, Depends(from_user_context("settings"))]
