# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI

from job_function_configurator.autogenerated_graphql_client import GraphQLClient
from job_function_configurator.config import get_settings
from job_function_configurator.events import events_router

fastapi_router = APIRouter()

logger = structlog.get_logger(__name__)

# The GraphQL client is generated from this version of the OS2mo schema, see
# "schema_path" in pyproject.toml.
GRAPHQL_VERSION = 21

MO_LISTENERS = [
    Listener(
        namespace="mo",
        user_key="job-function-configurator-engagement",
        routing_key="engagement",
        path="/events/mo/engagement",
    ),
]


def create_fastramqpi(**kwargs) -> FastRAMQPI:
    settings = get_settings()

    fastramqpi = FastRAMQPI(
        application_name="os2mo-job-function-configurator",
        settings=settings.fastramqpi,
        graphql_version=GRAPHQL_VERSION,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(declare_listeners=MO_LISTENERS),
    )

    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(fastapi_router)
    app.include_router(events_router)

    return fastramqpi


def create_app(**kwargs) -> FastAPI:
    fastramqpi = create_fastramqpi(**kwargs)
    return fastramqpi.get_app()
