# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
import structlog
from fastapi import APIRouter
from fastapi import FastAPI
from fastramqpi.events import GraphQLEvents
from fastramqpi.events import Listener
from fastramqpi.main import FastRAMQPI

from job_function_configurator.autogenerated_graphql_client import GraphQLClient
from job_function_configurator.config import get_settings
from job_function_configurator.events import events_router
from job_function_configurator.log import setup_logging

fastapi_router = APIRouter()

logger = structlog.get_logger(__name__)

MO_LISTENERS = [
    Listener(
        namespace="mo",
        user_key="job-function-configurator-engagement",
        routing_key="engagement",
        path="/events/mo/engagement",
    ),
]


def create_fastramqpi(**kwargs) -> FastRAMQPI:
    settings = get_settings()
    setup_logging(settings.log_level)

    fastramqpi = FastRAMQPI(
        application_name="os2mo-job-function-configurator",
        settings=settings,
        graphql_version=settings.mo_graphql_version,
        graphql_client_cls=GraphQLClient,
        graphql_events=GraphQLEvents(declare_listeners=MO_LISTENERS),
    )

    fastramqpi.add_context(settings=settings)

    app = fastramqpi.get_app()
    app.include_router(fastapi_router)
    app.include_router(events_router)

    return fastramqpi


def create_app(**kwargs) -> FastAPI:
    fastramqpi = create_fastramqpi(**kwargs)
    return fastramqpi.get_app()
