# SPDX-FileCopyrightText: 2023 Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
from uuid import UUID

import structlog
from more_itertools import one
from more_itertools import only

from job_function_configurator.autogenerated_graphql_client import (
    EngagementUpdateInput,
)
from job_function_configurator.autogenerated_graphql_client import GraphQLClient
from job_function_configurator.autogenerated_graphql_client import RAValidityInput
from job_function_configurator.config import JobFunctionSettings


logger = structlog.get_logger(__name__)


async def process_engagement_events(
    mo: GraphQLClient, settings: JobFunctionSettings, engagement_uuid: UUID
) -> None:
    """
    A function for handling the various events made involving an engagement.
    This involves checking whether the engagement has a job function containing
    sensitive information, and to potentially overwrite this information.

    Args:
        mo: A MO graphql client used to perform queries and mutations to MO.
        settings: The integration settings
        engagement_uuid: UUID of the engagement
    """
    logger.info("Processing an engagement event")

    engagement_object_response = await mo.get_engagement(
        engagement_uuid, settings.itsystem_user_key
    )
    # As we lookup by UUID we expect at most 1 result
    engagement_object = only(engagement_object_response.objects)
    # If no objects were found in the GraphQL payload, it was probably a termination.
    if engagement_object is None:
        logger.info("Engagement objects are missing")
        return
    engagement = engagement_object.current
    if engagement is None:
        logger.warn("Engagement current empty")
        return

    person = one(engagement.person)
    has_ituser = bool(person.itusers)

    is_primary = engagement.is_primary
    has_extension2 = bool(engagement.extension_2)

    job_function_blacklisted = (
        engagement.job_function.user_key in settings.blacklisted_keys
    )

    logger.info(f"ITUser was{'' if has_ituser else ' not'} found")
    if is_primary and has_ituser and has_extension2:
        new_job_function = engagement.extension_2
        source = "extension_2"
    elif job_function_blacklisted:
        new_job_function = settings.empty_content_for_extension_field_update
        source = "empty-value"
    else:
        new_job_function = engagement.job_function.name
        source = "job-function"
    logger.info(
        "Found job function source",
        source=source,
        has_ituser=has_ituser,
        is_primary=is_primary,
        has_extension2=has_extension2,
        job_function_blacklisted=job_function_blacklisted,
    )

    if new_job_function is None:
        logger.info("The desired job function is None, clearing the field")
        new_job_function = settings.empty_content_for_extension_field_update

    if engagement.extension_3 == new_job_function:
        logger.info("Engagement already has the desire job function")
        return

    # Write the engagement back as it is, with the new contents of extension_3.
    # Every field is written back explicitly, and over the validity of the
    # current period only, so nothing else about the engagement changes.
    await mo.update_engagement(
        EngagementUpdateInput(
            uuid=engagement_uuid,
            validity=RAValidityInput(
                from_=engagement.validity.from_,
                to=engagement.validity.to,
            ),
            user_key=engagement.user_key,
            primary=engagement.primary.uuid if engagement.primary is not None else None,
            person=one(engagement.person).uuid,
            org_unit=one(engagement.org_unit).uuid,
            engagement_type=engagement.engagement_type.uuid,
            job_function=engagement.job_function.uuid,
            extension_1=engagement.extension_1,
            extension_2=engagement.extension_2,
            extension_3=new_job_function,
            extension_4=engagement.extension_4,
            extension_5=engagement.extension_5,
            extension_6=engagement.extension_6,
            extension_7=engagement.extension_7,
            extension_8=engagement.extension_8,
            extension_9=engagement.extension_9,
            extension_10=engagement.extension_10,
        )
    )
    logger.info("The job function has been written to extension_3")
