# Generated by ariadne-codegen on 2023-10-31 17:47
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional, Union
from uuid import UUID

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .get_engagement import GetEngagement, GetEngagementEngagements
from .update_extension_field import (
    UpdateExtensionField,
    UpdateExtensionFieldEngagementUpdate,
)


def gql(q: str) -> str:
    return q


class GraphQLClient(AsyncBaseClient):
    async def get_engagement(
        self,
        engagement_uuid: UUID,
        email_user_keys: Union[Optional[List[str]], UnsetType] = UNSET,
    ) -> GetEngagementEngagements:
        query = gql(
            """
            query GetEngagement($engagement_uuid: UUID!, $email_user_keys: [String!]) {
              engagements(filter: {uuids: [$engagement_uuid]}) {
                objects {
                  current {
                    validity {
                      from
                      to
                    }
                    extension_2
                    extension_3
                    is_primary
                    job_function {
                      name
                      user_key
                      uuid
                    }
                    primary {
                      name
                      user_key
                      uuid
                    }
                    person {
                      uuid
                      addresses(filter: {address_type_user_keys: $email_user_keys}) {
                        name
                        user_key
                        address_type {
                          scope
                          user_key
                          name
                        }
                      }
                    }
                  }
                  uuid
                }
              }
            }
            """
        )
        variables: dict[str, object] = {
            "engagement_uuid": engagement_uuid,
            "email_user_keys": email_user_keys,
        }
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return GetEngagement.parse_obj(data).engagements

    async def update_extension_field(
        self,
        uuid: UUID,
        from_date: datetime,
        to_date: Union[Optional[datetime], UnsetType] = UNSET,
        extension_3: Union[Optional[str], UnsetType] = UNSET,
    ) -> UpdateExtensionFieldEngagementUpdate:
        query = gql(
            """
            mutation UpdateExtensionField($uuid: UUID!, $from_date: DateTime!, $to_date: DateTime, $extension_3: String) {
              engagement_update(
                input: {uuid: $uuid, validity: {from: $from_date, to: $to_date}, extension_3: $extension_3}
              ) {
                uuid
              }
            }
            """
        )
        variables: dict[str, object] = {
            "uuid": uuid,
            "from_date": from_date,
            "to_date": to_date,
            "extension_3": extension_3,
        }
        response = await self.execute(query=query, variables=variables)
        data = self.get_data(response)
        return UpdateExtensionField.parse_obj(data).engagement_update
