# Generated by ariadne-codegen on 2023-10-31 18:54
# Source: queries.graphql

from typing import List, Optional
from uuid import UUID

from .base_model import BaseModel


class GetItsystemUuid(BaseModel):
    itsystems: "GetItsystemUuidItsystems"


class GetItsystemUuidItsystems(BaseModel):
    objects: List["GetItsystemUuidItsystemsObjects"]


class GetItsystemUuidItsystemsObjects(BaseModel):
    current: Optional["GetItsystemUuidItsystemsObjectsCurrent"]


class GetItsystemUuidItsystemsObjectsCurrent(BaseModel):
    uuid: UUID
    user_key: str


GetItsystemUuid.update_forward_refs()
GetItsystemUuidItsystems.update_forward_refs()
GetItsystemUuidItsystemsObjects.update_forward_refs()
GetItsystemUuidItsystemsObjectsCurrent.update_forward_refs()
