# Generated by ariadne-codegen on 2023-10-31 18:54
# Source: queries.graphql

from datetime import datetime
from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetEngagement(BaseModel):
    engagements: "GetEngagementEngagements"


class GetEngagementEngagements(BaseModel):
    objects: List["GetEngagementEngagementsObjects"]


class GetEngagementEngagementsObjects(BaseModel):
    current: Optional["GetEngagementEngagementsObjectsCurrent"]


class GetEngagementEngagementsObjectsCurrent(BaseModel):
    validity: "GetEngagementEngagementsObjectsCurrentValidity"
    extension_2: Optional[str]
    extension_3: Optional[str]
    is_primary: bool
    job_function: "GetEngagementEngagementsObjectsCurrentJobFunction"
    person: List["GetEngagementEngagementsObjectsCurrentPerson"]


class GetEngagementEngagementsObjectsCurrentValidity(BaseModel):
    from_: datetime = Field(alias="from")
    to: Optional[datetime]


class GetEngagementEngagementsObjectsCurrentJobFunction(BaseModel):
    name: str
    user_key: str


class GetEngagementEngagementsObjectsCurrentPerson(BaseModel):
    itusers: List["GetEngagementEngagementsObjectsCurrentPersonItusers"]


class GetEngagementEngagementsObjectsCurrentPersonItusers(BaseModel):
    user_key: str


GetEngagement.update_forward_refs()
GetEngagementEngagements.update_forward_refs()
GetEngagementEngagementsObjects.update_forward_refs()
GetEngagementEngagementsObjectsCurrent.update_forward_refs()
GetEngagementEngagementsObjectsCurrentValidity.update_forward_refs()
GetEngagementEngagementsObjectsCurrentJobFunction.update_forward_refs()
GetEngagementEngagementsObjectsCurrentPerson.update_forward_refs()
GetEngagementEngagementsObjectsCurrentPersonItusers.update_forward_refs()
