# Generated by ariadne-codegen on 2023-07-27 14:13
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateJobFunction(BaseModel):
    engagement_update: "UpdateJobFunctionEngagementUpdate"


class UpdateJobFunctionEngagementUpdate(BaseModel):
    uuid: UUID


UpdateJobFunction.update_forward_refs()
UpdateJobFunctionEngagementUpdate.update_forward_refs()
